### ISSUE TITLE
회원가입 및 로그인 기능 테스트

### ISSUE THREAD

**Issue by KwonYeJun** [kongukjae/KDT-2-Project-C-2#12]
회원가입 시 작성된 데이터를 DB로 전송.
로그인 시도 시 작성된 데이터와 DB 데이터 비교.

**Comment by krapli441** [comment]
2023년 4월 20일 기준 origin/krapli441/issue12 브랜치에서 로그인 로직 제작 중.

**Comment by krapli441** [comment]
2023년 4월 21일 기준
로그인 로직 제작 완료.
회원가입 로직 제작 완료.

(버그 수정과 회원가입 실패 페이지 등은 아직 남아있는 상태)

로직에 대한 부분은 제작 되었기 때문에 이슈를 닫겠습니다.
