### ISSUE TITLE
채팅 기능에 필요한 기능 연구

### ISSUE THREAD

**Issue by krapli441** [kongukjae/KDT-2-Project-C-2#25]
메인 브랜치에 /root/prac/chatting_research 라는 폴더를 만들었습니다.
main 브랜치에서 pull을 해주신 뒤
해당 폴더 안에서 채팅에 관한 기능에 대해 연구한 것들을 기록하시면 됩니다.
(브랜치도 마음껏 생성하고 전환하는 연습하면 좋을 것 같습니다.)

**Comment by KwonYeJun** [comment]
넵
