### ISSUE TITLE
DB 설계 readME 작성하기

### ISSUE THREAD

**Issue by KwakYounHo** [kongukjae/KDT-2-Project-C-2#3]
프로젝트의 시작 지점 DB 설계 README.md 작성하기

**Comment by KwakYounHo** [comment]
https://github.com/kongukjae/KDT-2-Project-C-2/tree/KwakYounHo/issue3

**Comment by KwonYeJun** [comment]
Test

**Comment by HaekyungS** [comment]
1. database 이름 : IA 바로 하단 줄 IA 를 임시로 선정하게 된 계기에 문맥상 정정이 필요하다 생각합니다.
    (현재) IA를 구글에 검색하면 나오는 결과가 '이야'가 인상이 깊었기에
    (수정) IA를 구글에 검색하였을 때 나온 결과인 '이야'가 인상이 깊었기에

2. DB접속계정 부분의 admin_개발자 에 대한 설명 두번째에 자칫하면 table권한 부여를 하지 못한다는 인식이 들 수 있다 생각합니다. 이에 .* 을 붙이지 않아 생긴 시행착오를 기재하는 방식으로 정정하면 좋을 것 같습니다.
   (현재) DB로 접속 권한만 설정 하였고, table 등 권한을 부여하지 못해 워크벤치로 해결하였고, 이를 추후 개인 연습을 통해 테이블의 권한까지 CLI로 부여하는 것을 연습하기로 결정.
   (수정) CLI로 접속 권한 설정하였으나 query문 기재 시 DB에 대한 권한만 부여하고 table에 대한 권한부여를 놓쳤으며, 워크벤치 작업 중 알게되어 워크벤치로 추가적인 권한부여 작업을 진행함. 이 부분에 대해서는 추후 개인 연습을 통해 테이블의 권한까지 CLI로 부여하는 것을 연습하기로 결정

=> 23.04.03 저는 위와 같이 정정 의견이 있어 작성드리오니 확인 부탁드립니다.

**Comment by krapli441** [comment]
'프로젝트 목표' 부분 내용
90 ~ 00년대 사람에게 친숙한 매체인 포켓몬스터와 디지몬 api를 활용하여 지인 또는 처음 보는 사람들과 자유롭게 소통할 수 있는 공간 제작

이라고 추가. pull request 드리려고 했는데 commit change를 해 버렸습니다. 죄송합니다!!!

**Comment by KwakYounHo** [comment]
-----반영 했습니다-----
